namespace iDock;

internal static partial class UiText
{
    static partial void AddWindowEntries(Dictionary<string, Translation> entries)
    {
        entries.Add("Header.Tagline", new("Perangkat Anda. Ruang kerja yang sama.", "Your device. One workspace."));
        entries.Add("Session.Stop", new("Hentikan sesi", "Stop session"));
        entries.Add("Session.StopAccessible", new("Hentikan sesi mirroring dan kontrol", "Stop the mirroring and control session"));
        entries.Add("Guide.Title", new("Panduan", "Guide"));
        entries.Add("Guide.Intro", new("Siapkan koneksi dalam tiga langkah.", "Connect in three simple steps."));
        entries.Add("Guide.NetworkTitle", new("Jaringan yang sama", "Same network"));
        entries.Add("Guide.NetworkBody", new("Hubungkan perangkat dan Windows ke Wi-Fi yang sama, lalu klik Buka mirroring.", "Connect your device and Windows to the same Wi-Fi, then click Open mirroring."));
        entries.Add("Guide.ScreenTitle", new("Bagikan layar", "Share your screen"));
        entries.Add("Guide.ScreenPrefix", new("Di perangkat: Control Center → Screen Mirroring → ", "On your device: Control Center → Screen Mirroring → "));
        entries.Add("Guide.ControlTitle", new("Hubungkan kontrol", "Connect controls"));
        entries.Add("Guide.ControlBody", new("Klik Aktifkan kontrol. Buka Settings → Accessibility → Touch → AssistiveTouch, lalu aktifkan. Pilih Devices → Bluetooth Devices dan pasangkan:", "Click Enable control. Open Settings → Accessibility → Touch → AssistiveTouch and turn it on. Select Devices → Bluetooth Devices and pair with:"));
        entries.Add("Guide.LoadingName", new("Memuat nama laptop…", "Loading laptop name…"));
        entries.Add("Shortcut.Switch", new("  Alihkan target input     ·     ", "  Switch input target     ·     "));
        entries.Add("Shortcut.Return", new("  Kembali ke Windows", "  Return to Windows"));
        entries.Add("Mirror.Title", new("Layar perangkat", "Device screen"));
        entries.Add("Mirror.Description", new("Layar iPhone atau iPad, langsung di laptop melalui AirPlay.", "Your iPhone or iPad screen, live on your laptop with AirPlay."));
        entries.Add("Mirror.NotStarted", new("Belum dimulai", "Not started"));
        entries.Add("Mirror.Open", new("Buka mirroring", "Open mirroring"));
        entries.Add("Mirror.SeparateWindow", new("Video terbuka di jendela terpisah.", "Video opens in a separate window."));
        entries.Add("Mirror.Opened", new("Penerima AirPlay dibuka — pilih uxplay-windows di perangkat", "AirPlay receiver opened — select uxplay-windows on your device"));
        entries.Add("Mirror.Stopped", new("Sesi dihentikan", "Session stopped"));
        entries.Add("Mirror.VideoEnded", new("Sesi dihentikan — jendela video telah berakhir", "Session stopped — the video window has ended"));
        entries.Add("Mirror.ReceiverEnded", new("Receiver berhenti — sesi dihentikan", "Receiver exited — session stopped"));
        entries.Add("Control.Title", new("Mouse & keyboard", "Mouse & keyboard"));
        entries.Add("Control.Description", new("Klik, scroll, dan ketik dengan Bluetooth HID dan AssistiveTouch.", "Click, scroll, and type with Bluetooth HID and AssistiveTouch."));
        entries.Add("Control.NotConnected", new("Belum terhubung", "Not connected"));
        entries.Add("Control.Enable", new("Aktifkan kontrol", "Enable control"));
        entries.Add("Control.Check", new("Cek Bluetooth", "Check Bluetooth"));
        entries.Add("Settings.Title", new("Pengaturan", "Settings"));
        entries.Add("Settings.Description", new("Sesuaikan bahasa dan gerakan dengan cara Anda bekerja.", "Choose your language and adjust pointer movement."));
        entries.Add("Sensitivity.Title", new("Sensitivitas pointer", "Pointer sensitivity"));
        entries.Add("Sensitivity.Reset", new("Reset", "Reset"));
        entries.Add("Sensitivity.ResetAccessible", new("Reset sensitivitas ke 1 kali", "Reset sensitivity to normal (1×)"));
        entries.Add("Sensitivity.Accessible", new("Sensitivitas gerakan pointer perangkat", "Device pointer movement sensitivity"));
        entries.Add("Sensitivity.Tooltip", new("0.25× lebih pelan · 1.00× normal · 3.00× lebih cepat", "0.25× slower · 1.00× normal · 3.00× faster"));
        entries.Add("Sensitivity.Fast", new("Cepat · 3.00×", "Fast · 3.00×"));
        entries.Add("Sensitivity.Slow", new("Pelan · 0.25×", "Slow · 0.25×"));
        entries.Add("Sensitivity.AutoSaved", new("Tersimpan otomatis · klik dan scroll tetap.", "Saved automatically · clicks and scrolling stay unchanged."));
        entries.Add("Sensitivity.LoadFailed", new("Pengaturan gagal dibaca; ubah kontrol untuk menyimpan ulang.", "Could not read settings; adjust a control to save again."));
        entries.Add("Sensitivity.Saving", new("Menyimpan…", "Saving…"));
        entries.Add("Sensitivity.ChooseOrientation", new("Pilih orientasi kontrol untuk menyimpan pengaturan.", "Choose a control orientation to save your settings."));
        entries.Add("Sensitivity.Saved", new("Tersimpan · dibaca otomatis saat kontrol aktif.", "Saved · applied automatically while control is active."));
        entries.Add("Sensitivity.SaveFailed", new("Gagal menyimpan; nilai kontrol sebelumnya tetap dipakai.", "Could not save; the previous control settings remain in use."));
        entries.Add("Orientation.Title", new("Orientasi kontrol", "Control orientation"));
        entries.Add("Orientation.Description", new("Sesuaikan posisi perangkat", "Match your device position"));
        entries.Add("Orientation.Accessible", new("Orientasi arah gerakan pointer perangkat", "Device pointer movement orientation"));
        entries.Add("Orientation.Portrait", new("Portrait · posisi normal", "Portrait · normal position"));
        entries.Add("Orientation.Left", new("Landscape · sisi atas di kiri", "Landscape · top edge on the left"));
        entries.Add("Orientation.Right", new("Landscape · sisi atas di kanan", "Landscape · top edge on the right"));
        entries.Add("Orientation.UpsideDown", new("Portrait terbalik · sisi atas di bawah", "Upside-down portrait · top edge at the bottom"));
        entries.Add("Orientation.Note", new("Rotasi manual · acuan sisi atas saat portrait.", "Manual rotation · use the top edge in portrait as your reference."));
        entries.Add("Language.Title", new("Bahasa", "Language"));
        entries.Add("Language.Description", new("Bahasa antarmuka aplikasi", "Application interface language"));
        entries.Add("Language.Accessible", new("Pilih bahasa antarmuka iDock", "Choose the iDock interface language"));
        entries.Add("Language.AutoSaved", new("Pilihan bahasa tersimpan otomatis.", "Your language preference is saved automatically."));
        entries.Add("Language.Saved", new("Bahasa tersimpan · sesi dan pengaturan pointer tetap.", "Language saved · your session and pointer settings are unchanged."));
        entries.Add("Language.Preview", new("Pratinjau bahasa · tidak disimpan.", "Language preview · not saved."));
        entries.Add("Language.LoadFailed", new("Bahasa tersimpan gagal dibaca; Bahasa Indonesia digunakan. {0}", "Could not read the saved language; using Indonesian. {0}"));
        entries.Add("Language.SaveFailed", new("Bahasa berubah untuk sesi ini, tetapi gagal disimpan. {0}", "Language changed for this session, but could not be saved. {0}"));
        entries.Add("Diagnostic.Title", new("Diagnostik", "Diagnostics"));
        entries.Add("Diagnostic.Ready", new("Siap. Mulai dari mirroring, lalu cek koneksi Bluetooth.", "Ready. Start mirroring, then check the Bluetooth connection."));
        entries.Add("Diagnostic.OpenLogs", new("Buka log", "Open logs"));
        entries.Add("Diagnostic.LogAccessible", new("Log sesi iDock", "iDock session log"));
        entries.Add("Diagnostic.Privacy", new("Log tersimpan di Windows Anda. Tidak diunggah otomatis.", "Logs stay on your Windows PC. They are not uploaded automatically."));
        entries.Add("Diagnostic.Checking", new("Memeriksa adapter dan kemampuan Bluetooth…", "Checking the adapter and Bluetooth capabilities…"));
        entries.Add("Diagnostic.Error", new("Operasi gagal: {0}", "Operation failed: {0}"));
        entries.Add("Diagnostic.CleanupFailed", new("Pembersihan sesi Bluetooth belum terkonfirmasi. Tutup {0} dan periksa log sebelum mencoba lagi.", "Bluetooth session cleanup is not confirmed. Close {0} and check the logs before trying again."));
        entries.Add("Diagnostic.ExistingLink", new("Koneksi HID lama terverifikasi; iklan Bluetooth belum siap. Mulai kontrol dan uji input perangkat.", "Existing HID connection verified; Bluetooth advertising is not ready. Enable control and test device input."));
        entries.Add("Diagnostic.Limited", new("Iklan Bluetooth terbatas. Penemuan perangkat, pairing, dan input masih perlu diuji.", "Bluetooth advertising is limited. Device discovery, pairing, and input still need testing."));
        entries.Add("Diagnostic.Advertising", new("Bluetooth bisa mengiklankan mouse/keyboard. Pairing dan input perangkat masih perlu diuji.", "Bluetooth can advertise a mouse/keyboard. Pairing and device input still need testing."));
        entries.Add("Diagnostic.Access", new("Pemeriksaan terhalang akses Windows. Lihat log; ini belum berarti adapter tidak mendukung.", "The check was blocked by Windows access permissions. See the logs; this does not yet mean the adapter is unsupported."));
        entries.Add("Diagnostic.Unsupported", new("Adapter tidak mendukung mode kontrol. Mirroring tetap dapat digunakan.", "The adapter does not support control mode. Mirroring is still available."));
        entries.Add("Diagnostic.NotReady", new("Bluetooth belum siap. Lihat log untuk kondisi adapter, izin, dan status radio.", "Bluetooth is not ready. Check the logs for adapter, permission, and radio status."));
        entries.Add("Footer.Local", new("Koneksi lokal · Tanpa akun · Tidak berafiliasi dengan Apple", "Local connection · No account · Not affiliated with Apple"));
        entries.Add("Footer.RepositoryAccessible", new("Buka repository iDock di GitHub", "Open the iDock repository on GitHub"));
        entries.Add("Footer.Issues", new("Laporkan masalah", "Report an issue"));
        entries.Add("Footer.IssuesAccessible", new("Laporkan masalah di GitHub", "Report an issue on GitHub"));
        entries.Add("Error.OpenLink", new("Tautan tidak dapat dibuka. {0}", "Could not open the link. {0}"));
        entries.Add("Log.PointerLoadFailed", new("Pengaturan pointer gagal dibaca: {0}", "Could not read pointer settings: {0}"));
        entries.Add("Log.PointerSaveFailed", new("Pengaturan pointer gagal disimpan: {0}", "Could not save pointer settings: {0}"));
        entries.Add("Log.Startup", new("{0} {1} — startup Bluetooth memeriksa iklan dan koneksi HID secara terpisah.", "{0} {1} — Bluetooth startup checks advertising and HID connections separately."));
        entries.Add("Log.MirrorOpened", new("UxPlay dibuka. Tampilan video muncul setelah Screen Mirroring tersambung. Setup awal mungkin meminta instalasi Bonjour.", "UxPlay opened. Video appears after Screen Mirroring connects. Initial setup may ask to install Bonjour."));
        entries.Add("Log.ControlStarted", new("Input tetap di laptop. Setelah pairing, Ctrl+D+C memilih perangkat; Ctrl+Alt+Q kembali ke laptop.", "Input stays on the laptop. After pairing, Ctrl+D+C selects the device; Ctrl+Alt+Q returns to the laptop."));
        entries.Add("Log.SessionStopped", new("Sesi {0} dihentikan.", "The {0} session was stopped."));
        entries.Add("Log.SessionCleanup", new("{0} Input kembali ke laptop. Pairing, pengaturan, dan layanan Bonjour tetap tersimpan.", "{0} Input returns to the laptop. Pairing, settings, and Bonjour Service are retained."));
        entries.Add("Log.VideoReadFailed", new("Status jendela video belum dapat dibaca. Sesi tetap berjalan; gunakan Hentikan sesi jika diperlukan.", "Could not read the video window status. The session remains active; use Stop session if needed."));
        entries.Add("Log.VideoEnded", new("Jendela video tidak ada selama 2 detik; sesi mirroring dan kontrol dihentikan.", "The video window was absent for 2 seconds; the mirroring and control session was stopped."));
        entries.Add("Log.ReceiverEnded", new("Proses receiver berakhir. Jika setup Bonjour baru selesai, buka mirroring lagi.", "The receiver process exited. If Bonjour setup just finished, open mirroring again."));
        entries.Add("Log.MirrorWatchFailed", new("Pemantauan mirroring: {0}", "Mirroring watcher: {0}"));
        entries.Add("Log.ControlEnded", new("Proses Bluetooth berhenti. Lihat log atau jalankan Cek Bluetooth.", "The Bluetooth process exited. See the logs or run Check Bluetooth."));
        entries.Add("Log.CloseCleanupFailed", new("Sesi gagal dibersihkan saat menutup: {0}", "Could not clean up the session while closing: {0}"));
    }
}
